-- liquibase formatted sql

-- changeset mikhail:1690-1
CREATE TABLE "order"
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    phone_number   VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    address       VARCHAR(255)                            NOT NULL,
    date_created  TIMESTAMP DEFAULT now(),
    CONSTRAINT "order_pkey" PRIMARY KEY (id)
);